"""car transport

Revision ID: ac95df26e3e9
Revises: 06dbd1a87d4e
Create Date: 2024-04-30 12:12:35.447988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac95df26e3e9'
down_revision: Union[str, None] = '06dbd1a87d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transport', sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('transport', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('transport', sa.Column('date_from', sa.DateTime(), nullable=True))
    op.add_column('transport', sa.Column('date_to', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transport', 'date_to')
    op.drop_column('transport', 'date_from')
    op.drop_column('transport', 'updated_at')
    op.drop_column('transport', 'created_on')
    # ### end Alembic commands ###
