"""car transport added car_id

Revision ID: 06dbd1a87d4e
Revises: bb8bc7de42b1
Create Date: 2024-04-24 12:29:59.362347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06dbd1a87d4e'
down_revision: Union[str, None] = 'bb8bc7de42b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_transport_id_fkey', 'car', type_='foreignkey')
    op.drop_column('car', 'transport_id')
    op.add_column('transport', sa.Column('car_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transport', 'car', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transport', type_='foreignkey')
    op.drop_column('transport', 'car_id')
    op.add_column('car', sa.Column('transport_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('car_transport_id_fkey', 'car', 'transport', ['transport_id'], ['id'])
    # ### end Alembic commands ###
